import { Building2, Coins, DatabaseBackup, FileDigit, ImagePlus, Save, ShieldCheck } from 'lucide-react';
import { useState, type ChangeEvent, type FormEvent } from 'react';
import { Button } from '../components/ui/Button';
import { Modal } from '../components/ui/Modal';
import { PageHeader } from '../components/ui/PageHeader';
import { useApp } from '../context/AppContext';
import type { CompanySettings, CurrencyCode } from '../types/models';
import { getCurrencyLocale } from '../utils/money';

export function SettingsPage() {
  const { data: nullableData, saveSettings, resetDemo, notify } = useApp();
  const data = nullableData!;
  const [form, setForm] = useState<CompanySettings>(() => structuredClone(data.settings));
  const [saving, setSaving] = useState(false);
  const [resetOpen, setResetOpen] = useState(false);
  const [resetting, setResetting] = useState(false);
  const currentYear = new Date().getFullYear();
  const set = <K extends keyof CompanySettings>(key: K, value: CompanySettings[K]) => setForm((current) => ({ ...current, [key]: value }));
  const setAddress = (key: keyof CompanySettings['address'], value: string) => set('address', { ...form.address, [key]: value });
  const setRange = (key: keyof CompanySettings['numberRanges'], value: string | number) => set('numberRanges', { ...form.numberRanges, [key]: value });

  async function submit(event: FormEvent) { event.preventDefault(); if (!form) return; setSaving(true); await saveSettings(form); setSaving(false); }
  async function confirmReset() { setResetting(true); await resetDemo(); setResetting(false); setResetOpen(false); }
  function changeCurrency(currency: CurrencyCode) { setForm((current) => ({ ...current, currency, locale: getCurrencyLocale(currency) })); }
  function uploadLogo(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return;
    if (!['image/png', 'image/jpeg'].includes(file.type)) { notify('Bitte verwenden Sie ein PNG- oder JPG-Bild.', 'danger'); return; }
    if (file.size > 500_000) { notify('Das Logo darf maximal 500 KB gross sein.', 'danger'); return; }
    const reader = new FileReader(); reader.onload = () => set('logo', String(reader.result)); reader.onerror = () => notify('Das Logo konnte nicht gelesen werden.', 'danger'); reader.readAsDataURL(file);
  }

  return <div className="page settings-page"><PageHeader eyebrow="System" title="Einstellungen" description="Unternehmensdaten, Finanzen und Nummernkreise zentral konfigurieren." />
    <form onSubmit={submit} className="settings-layout">
      <nav className="settings-nav"><a href="#unternehmen"><Building2 size={17}/>Unternehmen</a><a href="#finanzen"><Coins size={17}/>Finanzen</a><a href="#nummernkreise"><FileDigit size={17}/>Nummernkreise</a><a href="#demo-daten"><DatabaseBackup size={17}/>Demo-Daten</a></nav>
      <div className="settings-content">
        <section className="settings-section" id="unternehmen"><div className="settings-section__head"><span><Building2 size={20}/></span><div><h2>Unternehmen</h2><p>Diese Angaben werden auf Dokumenten und Korrespondenz verwendet.</p></div></div><div className="settings-section__body"><div className="logo-upload"><div className="logo-preview">{form.logo ? <img src={form.logo} alt="Firmenlogo" /> : <strong>M</strong>}</div><div><strong>Firmenlogo</strong><p>PNG oder JPG, maximal 500 KB</p><label className="button button--secondary"><ImagePlus size={16}/><span>Logo auswählen</span><input type="file" accept="image/png,image/jpeg" onChange={uploadLogo} hidden /></label></div></div><div className="form-grid"><label className="field field--full"><span>Firmenname</span><input value={form.companyName} onChange={(e) => set('companyName', e.target.value)} required /></label><label className="field field--full"><span>Branche / Leistungsbereich</span><input value={form.industry} onChange={(e) => set('industry', e.target.value)} /></label><label className="field field--full"><span>Strasse und Hausnummer</span><input value={form.address.street} onChange={(e) => setAddress('street', e.target.value)} required /></label><label className="field"><span>PLZ</span><input value={form.address.postalCode} onChange={(e) => setAddress('postalCode', e.target.value)} required /></label><label className="field"><span>Ort</span><input value={form.address.city} onChange={(e) => setAddress('city', e.target.value)} required /></label><label className="field"><span>Land</span><input value={form.address.country} onChange={(e) => setAddress('country', e.target.value)} required /></label><label className="field"><span>Telefon</span><input value={form.phone} onChange={(e) => set('phone', e.target.value)} /></label><label className="field"><span>E-Mail</span><input type="email" value={form.email} onChange={(e) => set('email', e.target.value)} /></label><label className="field"><span>Website</span><input value={form.website} onChange={(e) => set('website', e.target.value)} /></label><label className="field field--full"><span>UID / MwSt.-Nummer</span><input value={form.vatId} onChange={(e) => set('vatId', e.target.value)} /></label></div></div></section>
        <section className="settings-section" id="finanzen"><div className="settings-section__head"><span><Coins size={20}/></span><div><h2>Finanzen</h2><p>Standardwerte für neue Kostenvoranschläge und Rechnungen.</p></div></div><div className="settings-section__body"><div className="form-grid"><label className="field field--full"><span>Standardwährung</span><select value={form.currency} onChange={(e) => changeCurrency(e.target.value as CurrencyCode)}><option value="CHF">CHF – Schweizer Franken</option><option value="EUR">EUR – Euro</option><option value="USD">USD – US-Dollar</option><option value="GBP">GBP – Britisches Pfund</option></select><small>Alle Beträge in der Anwendung werden unmittelbar in dieser Währung dargestellt.</small></label><label className="field"><span>Standard-MwSt. (%)</span><input type="number" step="0.1" min="0" value={form.defaultTaxRate} onChange={(e) => set('defaultTaxRate', Number(e.target.value))} /></label><label className="field"><span>Zahlungsziel (Tage)</span><input type="number" min="0" value={form.paymentTerms} onChange={(e) => set('paymentTerms', Number(e.target.value))} /></label><label className="field"><span>Standardrabatt (%)</span><input type="number" step="0.5" min="0" max="100" value={form.defaultDiscount} onChange={(e) => set('defaultDiscount', Number(e.target.value))} /></label></div></div></section>
        <section className="settings-section" id="nummernkreise"><div className="settings-section__head"><span><FileDigit size={20}/></span><div><h2>Nummernkreise</h2><p>Präfixe und nächste laufende Nummern für neue Belege.</p></div></div><div className="settings-section__body"><div className="number-grid"><div><strong>Rechnungen</strong><label className="field"><span>Präfix</span><input value={form.numberRanges.invoicePrefix} onChange={(e) => setRange('invoicePrefix', e.target.value.toUpperCase())}/></label><label className="field"><span>Nächste Nummer</span><input type="number" value={form.numberRanges.nextInvoice} onChange={(e) => setRange('nextInvoice', Number(e.target.value))}/></label><small>Vorschau: {form.numberRanges.invoicePrefix}-{currentYear}-{String(form.numberRanges.nextInvoice).padStart(4, '0')}</small></div><div><strong>Kostenvoranschläge</strong><label className="field"><span>Präfix</span><input value={form.numberRanges.quotePrefix} onChange={(e) => setRange('quotePrefix', e.target.value.toUpperCase())}/></label><label className="field"><span>Nächste Nummer</span><input type="number" value={form.numberRanges.nextQuote} onChange={(e) => setRange('nextQuote', Number(e.target.value))}/></label><small>Vorschau: {form.numberRanges.quotePrefix}-{currentYear}-{String(form.numberRanges.nextQuote).padStart(4, '0')}</small></div><div><strong>Aufträge</strong><label className="field"><span>Präfix</span><input value={form.numberRanges.orderPrefix} onChange={(e) => setRange('orderPrefix', e.target.value.toUpperCase())}/></label><label className="field"><span>Nächste Nummer</span><input type="number" value={form.numberRanges.nextOrder} onChange={(e) => setRange('nextOrder', Number(e.target.value))}/></label><small>Vorschau: {form.numberRanges.orderPrefix}-{currentYear}-{String(form.numberRanges.nextOrder).padStart(4, '0')}</small></div></div></div></section>
        <section className="settings-section settings-section--danger" id="demo-daten"><div className="settings-section__head"><span><DatabaseBackup size={20}/></span><div><h2>Demo-Daten</h2><p>Ausgangszustand für Vorführungen wiederherstellen.</p></div></div><div className="settings-section__body"><div className="reset-row"><div><strong>Demo vollständig zurücksetzen</strong><p>Alle lokalen Änderungen werden gelöscht und der ursprüngliche Datenbestand der Müller Haustechnik AG wird neu geladen.</p></div><Button type="button" variant="danger" onClick={() => setResetOpen(true)}>Demo zurücksetzen</Button></div><div className="local-note"><ShieldCheck size={18}/><span><strong>Ihre Daten bleiben lokal.</strong> Diese Demo nutzt ausschliesslich IndexedDB in diesem Browser und überträgt keine Daten.</span></div></div></section>
        <div className="settings-savebar"><span>Nicht gespeicherte Änderungen werden erst mit „Speichern“ übernommen.</span><Button type="submit" icon={Save} disabled={saving}>{saving ? 'Wird gespeichert …' : 'Einstellungen speichern'}</Button></div>
      </div>
    </form>
    <Modal open={resetOpen} onClose={() => setResetOpen(false)} title="Demo-Daten zurücksetzen?" description="Diese Aktion kann nicht rückgängig gemacht werden." size="small" footer={<><Button variant="secondary" onClick={() => setResetOpen(false)}>Abbrechen</Button><Button variant="danger" onClick={confirmReset} disabled={resetting}>{resetting ? 'Wird zurückgesetzt …' : 'Jetzt zurücksetzen'}</Button></>}><div className="confirm-content"><span><DatabaseBackup size={24}/></span><p>Alle von Ihnen erstellten oder geänderten lokalen Datensätze und Einstellungen werden durch den ursprünglichen Demo-Stand ersetzt.</p></div></Modal>
  </div>;
}
